---
cidr_networks:
  container: 172.16.65.0/24
  tunnel: 172.18.0.0/24
  storage: 172.16.64.0/24

used_ips:
  - "172.16.64.1,172.16.64.63"
  - "172.16.65.1,172.16.65.63"
  - "172.16.65.254"
  - "172.18.0.1,172.18.0.63"
  - "192.168.0.0,192.168.255.255"
  - "172.16.0.0,172.16.63.255"
  - "172.17.0.0,172.17.255.255"
  - "172.31.0.0,172.31.255.255"

global_overrides:
  internal_lb_vip_address: 172.16.65.63
  #
  # The below domain name must resolve to an IP address
  # in the CIDR specified in haproxy_keepalived_external_vip_cidr.
  # If using different protocols (https/http) for the public/internal
  # endpoints the two addresses must be different.
  #
  external_lb_vip_address: openstack.h-otter.net
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "500:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "2001:2199"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  com01:
    affinity:
      galera_container: 2
      rabbit_mq_container: 2 
    ip: 172.16.65.1
  misc01:
    ip: 172.16.65.2

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  com01:
    ip: 172.16.65.1
  misc01:
    ip: 172.16.65.2

# load balancer
# Ideally the load balancer should not use the Infrastructure hosts.
# Dedicated hardware is best for improved performance and security.
haproxy_hosts:
  com01:
    ip: 172.16.65.1

# rsyslog server
log_hosts:
  com01:
    ip: 172.16.65.1
  misc01:
    ip: 172.16.65.2
